
const ADD_MOVIE = 'ADD_MOVIE';
const EDIT_MOVIE = 'EDIT_MOVIE';
const DELETE_MOVIE = 'DELETE_MOVIE';
const GET_MOVIES = 'GET_MOVIES';


export {
    ADD_MOVIE,
    EDIT_MOVIE,
    DELETE_MOVIE,
    GET_MOVIES,
}